### ISSUE TITLE
Connection to CMU should be more prominent

### ISSUE THREAD

**Issue by capnrefsmmat** [cmu-delphi/www-main#119]
Right now, the only mention of CMU on the new home page is "CMU" under About in the footer. Probably something in the header should mention CMU, either with the CMU wordmark or a logo or something.

**Comment by tildechris** [comment]
I don't disagree, but this isn't blocker for today's release; moving to v2.  @Letsgohyde, can you put together a few options here?

**Comment by jennyxxdance** [comment]
Here's the CMU logo brand guidelines: https://www.cmu.edu/brand/brand-guidelines/visual-identity/logos.html

**Comment by jennyxxdance** [comment]
@capnrefsmmat @tildechris @Letsgohyde I brought some of the variations of CMU logo -- which do you believe should belong in the header? Also attached some examples for inspo
<img width="865" alt="Screen Shot 2020-12-03 at 1 44 37 AM" src="https://user-images.githubusercontent.com/66391749/100903383-2ebc4400-3509-11eb-848b-05738135e7f3.png">

<img width="922" alt="Screen Shot 2020-12-03 at 1 46 11 AM" src="https://user-images.githubusercontent.com/66391749/100903537-60350f80-3509-11eb-9fc1-38011abfca46.png">
<img width="918" alt="Screen Shot 2020-12-03 at 1 46 17 AM" src="https://user-images.githubusercontent.com/66391749/100903556-64612d00-3509-11eb-8200-ffb0f4859979.png">
<img width="922" alt="Screen Shot 2020-12-03 at 1 46 24 AM" src="https://user-images.githubusercontent.com/66391749/100903574-67f4b400-3509-11eb-8ee6-3b62ec7038e5.png">

**Comment by tildechris** [comment]
If we're going to have Delphi in the header, as per the guidelines, it sounds like we need to use a unit-mark. E.g. 

**Carnegie Mellon University**
The Delphi Research Group

Visually, I'd like something similar to what JHU does with a vertical bar, but we'd need the full unit-mark somewhere else on the page, (footer?)

Perhaps we could have

**CMU** | Delphi 

In the header and the full unit-mark in the footer.

**Comment by Letsgohyde** [comment]
I think we can close this since @sgratzl has applied this change :)
