### ISSUE TITLE
V2 Iteration: incorrect arrow placement

### ISSUE THREAD

**Issue by jennyxxdance** [cmu-delphi/www-main#126]
The arrows are currently on the bottom of the images -- but they should be towards the center of the image's height.
<img width="1440" alt="Screen Shot 2020-12-01 at 1 54 32 AM" src="https://user-images.githubusercontent.com/66391749/100639184-339dbe00-3378-11eb-8cfb-027214a31497.png">

**Comment by tildechris** [comment]
This is intended behavior.

Placement in the middle of the image was causing the text to overflow, so I moved them to the bottom.  See #117.

If you want we can use this issue to track updating the nav widgets to what is in the spec.  Thoughts?

**Comment by jennyxxdance** [comment]
@tildechris Would it be possible to hide the arrows for smaller widths and support "swipes" instead? I do believe that for mobile UI, we can control the carousel by supporting the swiping gesture to better engage with a carousel on a touchscreen. Since we have the small dots underneath it, the user can look at the images back and forth in a slideshow fashion by swiping. Also, the requirement to hit those tiny dots or the arrows on mobile view may be problematic in any UI.

**Comment by tildechris** [comment]
The UI already supports swipe gestures. I agree about not being able to click on the dots in a mobile view; they're more for a visual indication of where you are.

Yes, we should be able to hide the arrows, but do you think hiding them for small widths is better than just seeing them at the bottom of the slider?

**Comment by Letsgohyde** [comment]
+1 on the visual indicators point, no worries there. 

Since the dots are a good communicator for swipe interaction would be great if we can remove the the arrows on mobile. But I'm not super hung up on this. If it can be done that would be great :)

**Comment by tildechris** [comment]
@sgratzl, can you move the arrows back to the middle for desktop width and hide them for mobile widths?
