### ISSUE TITLE
V2 Iteration: inconsistent spacing and font/card sizes for Latest News 

### ISSUE THREAD

**Issue by jennyxxdance** [cmu-delphi/www-main#127]
Our current site:
<img width="1438" alt="Screen Shot 2020-12-01 at 2 00 30 AM" src="https://user-images.githubusercontent.com/66391749/100640237-89269a80-3379-11eb-8443-3b979edca699.png">

Proposed (to-do):

1. Bold the header "Latest News"
2. Readjust spacing between header and the card, and between font alignments within the card
3. Arrow for the Carousel (if possible? same as other arrow designs we have)
4. Bring the "Learn more -->" UI we implemented earlier by @sgratzl (I believe?)
5. Minimize the card size (currently it looks very spaced out vertically)

I listed a bunch above, what do you think?

<img width="1313" alt="Screen Shot 2020-12-01 at 2 03 03 AM" src="https://user-images.githubusercontent.com/66391749/100640329-a2c7e200-3379-11eb-9b51-666874cf895d.png">

**Comment by sgratzl** [comment]
is this still valid?

**Comment by sgratzl** [comment]
won't fix for now
