### ISSUE TITLE
team-page: Names should wrap

### ISSUE THREAD

**Issue by Letsgohyde** [cmu-delphi/www-main#128]
![image](https://user-images.githubusercontent.com/7318770/100651812-a7ee4800-330b-11eb-84a7-b79dd1cdc234.png)

**Comment by sgratzl** [comment]
how do you wanna wrap a single word? `Balasubramanian`?

**Comment by sgratzl** [comment]
@Letsgohyde I cannot think of a way to wrap a single word. So we could reduce the font size for all names or just use two members per row instead of three

**Comment by sgratzl** [comment]
won't fix for now
