### ISSUE TITLE
pixelated member photos

### ISSUE THREAD

**Issue by dfarrow0** [cmu-delphi/www-main#129]
Most member photos appear to be high-res. However fellow photos look very pixelated.

Using myself as an example, compare my "past member" photo at the bottom of the page with my "fellow" photo in the middle of the page:

https://release--cmu-delphi-main.netlify.app/about/team/images/david-farrow-500x500-min_hu5ac3a7d83ebe244e5504daa4d4ffc22d_69107_250x250_resize_q75_box.jpg

https://release--cmu-delphi-main.netlify.app/about/team/images/david-farrow_head-shot_hu70db67ff6bbbd5d72348666e95c0028f_52452_250x250_resize_box_2.png

It looks like latter is cropped, desaturated, pixelated, and has rounded corners.

**Comment by sgratzl** [comment]
fixed in latest dev https://cmu-delphi-main.netlify.app/about/team/
