### ISSUE TITLE
Landing Page: “Densify” in general

### ISSUE THREAD

**Issue by jennyxxdance** [cmu-delphi/www-main#136]
[Roni] Hero images are too big, typography is often too big especially on mobile. The goal is to have a bit more of an **academic feel**. Big hero images feel commercial without conveying a lot of information.

[Chris] see also for inspiration, compared to the about page with the large thundercloud image:
- https://returntolearn.ucsd.edu/dashboard/index.html
- https://med.stanford.edu/news/all-news/2020/11/how-new-hospital-benefited-patients-and-staff-in-pandemic-year.html
- https://coronavirus.jhu.edu/about

**Comment by sgratzl** [comment]
@Letsgohyde  can we close this or is anything open?

**Comment by sgratzl** [comment]
can we close this?
