### ISSUE TITLE
Covidcast change log is out-of-sync with github changelog.

### ISSUE THREAD

**Issue by tildechris** [cmu-delphi/www-main#138]
Now that we are deriving the www-covidcast changelog by inspecting the git commits, and auto-generating a draft:

https://github.com/cmu-delphi/www-covidcast/blob/main/CHANGELOG.md

It doesn't make a lot of sense to separately have markdown release notes in www-main.  This is especially acute since I missed copying over the notes for 1.11.0.

We should decide if we should just link to github and how we want to handle communicating this change log in the future.

**Comment by dlaliberte** [comment]
Basing the changelog on individual commits is bound to be much noisier then something based on pull requests.  I know that I now make many more commits with meaningless comments like "switching to another branch" (as a workaround for the lack of support for "workspaces"), but the pull requests are a useful and relevant summary of the resulting changes.

**Comment by tildechris** [comment]
The main unit is actually PRs and not commits for this reason.  PRs are technically merges in git, so the current code detects merges, then looks up the description from github (which is why you see me editing PR titles; they get into the changelog).

I'm quite happy with how that works actually.  You can see in the above link that the nitty gritty of commit to commit work is hidden behind PR titles in the changelog.

What's sub-optimal is that we have release notes in two places currently.  CHANGELOG.md in www-covidcast and in separate markdown files for each release in www-main.

**Comment by sgratzl** [comment]
one possible approach with CHANGELOG.md as main file
 1. copy all changelog files from www-main into the CHANGELOG.md creating one unified changelog
 1. link from the menu-item in the website directly to this file on GitHub
 1. configure release-it (https://github.com/release-it/release-it/blob/master/docs/github-releases.md#release-notes) to also take the changelog as input for generating the notes for the GitHub release text.

another approach with GitHub releases as main source
 1. copy all changelog files from www-main into their corresponding tags/releases on GitHub
 1. link from the menu-item in the website directly to the latest GitHub release page
 1. in the release branch we have a temporary changelog file which will be converted by release-it to GitHub release notes and also deletes the file again

**Comment by sgratzl** [comment]
main changelog is now https://github.com/cmu-delphi/www-covidcast/releases/

**Comment by sgratzl** [comment]
wontfix -> in the new menu structure (#359) the release notes will be removed in favor of the GitHub Release Notes of COVIDcast.
