### ISSUE TITLE
Icons in mobile nav menu are different colors

### ISSUE THREAD

**Issue by kateharwood** [cmu-delphi/www-main#139]
<img width="389" alt="Screen Shot 2020-12-02 at 3 01 35 PM" src="https://user-images.githubusercontent.com/14190352/100925027-6e564200-34af-11eb-8f28-4f0f32d946d3.png">

The top two icons are grey while the other icons are darker.

Also, I cannot reproduce this in devtools, but on my actual device the "about" icon is slightly cut off on the right side.

**Comment by sgratzl** [comment]
related to #140 the header and links have a different text color

**Comment by sgratzl** [comment]
is this still valid?

**Comment by kateharwood** [comment]
Cannot reproduce
