### ISSUE TITLE
Top level headers are not clickable in mobile nav menu

### ISSUE THREAD

**Issue by kateharwood** [cmu-delphi/www-main#140]
Top level navigation ("About" and "COVIDcast") are not clickable in mobile nav menu.

**Comment by sgratzl** [comment]
atm those headers are redundant to their first sub point, About -> Delphi Research Group, COVIDCast -> Map

**Comment by kateharwood** [comment]
They are clickable on desktop though. When I went on the site on mobile I spent a while wondering why the mobile nav menu wasn't working before realizing it was just those options that weren't clickable. It might be confusing for people - there's nothing to indicate they can't be clicked.
