### ISSUE TITLE
change netlify deployment branches

### ISSUE THREAD

**Issue by sgratzl** [cmu-delphi/www-main#152]
similar to covidcast:
- main -> production
- dev -> dev branch build
- release -> release branch build

atm. dev is the production version

**Comment by krivard** [comment]
We currently have a build hook for `release`; do you want one for `dev` or `main` as well?

**Comment by sgratzl** [comment]
I think we don't need build hooks (so to trigger a re-build without any source change using a POST request) for this repo

**Comment by krivard** [comment]
Done.
