### ISSUE TITLE
Problems with the new blog style 

### ISSUE THREAD

**Issue by ryantibs** [cmu-delphi/www-main#157]
Hi all particularly @tildechris @sgratzl @capnrefsmmat (not sure whether this is the right repo for this). 

The new blog style looks great in general but has a few problems.  Check out, for example:

https://delphi.cmu.edu/blog/2020/09/21/can-symptoms-surveys-improve-covid-19-forecasts/

Three things to mention: only the first is really a problem, the latter two are style issues.

1. It looks like inline math equations aren't being displayed at all.  Check out the sentence beneath the displayed math block of aligned equations (describing the various model setups).  There's clearly several inline math equations that are being omitted.

2. Check out the same displayed math block of aligned equations (describing the various model setups), it spills out quite a bit past the right text boundary and looks a bit ugly.  Anything we can do here?  

3. The text in all of the figures is being rendered a little weird.  First of all, it looks like a serif font, and second it looks vertically squished to me.  It looked much better to me in its "native" rendering, as it appears in an R notebook (or the previous blog style).

**Comment by sgratzl** [comment]
@ryantibs the delphi-blog repo has been deprecated since it has been merged with www-main. 

regarding 1 can you take a look at https://deploy-preview-153--cmu-delphi-main.netlify.app
regarding 2 and 3: can you look at the current dev version at https://cmu-delphi-main.netlify.app.

**Comment by ryantibs** [comment]
Thanks Sam.  Didn't realize this repo has been deprecated.  Continue discussion on this issue here anyway?  Or start a new one over in www-main?

Assuming we continue here ...

First preview: thanks that looks like it fixed it!

Second preview:
- text in the plots looks much better!
- displayed equation still spills over the text right boundary 
- overall the text width looks like it's been smaller here?

**Comment by sgratzl** [comment]
>     * overall the text width looks like it's been smaller here?

@Letsgohyde can you comment on that. As far as I can see, the current version reflects your design

**Comment by ryantibs** [comment]
Thanks @sgratzl appreciate the replies.

@Letsgohyde @tildechris Can you explain why the text width narrowed?  I prefer the previous style (a little wider).  In the new style, the text is so narrow that the plots stick way out.

**Comment by ryantibs** [comment]
Hi @sgratzl I noticed one more small thing that could be addressed (sorry to tack on to this issue).  Take a look at the hovering table of contents panel here: https://delphi.cmu.edu/blog/2020/10/12/new-and-improved-covid-symptom-survey-tracks-testing-and-mask-wearing/.  

For the second-level headings, can we use a. b. c. or i. ii. iii. etc?  To distinguish from the 1. 2. 3. used in the first-level headings.

**Comment by sgratzl** [comment]
> For the second-level headings, can we use a. b. c. or i. ii. iii. etc? To distinguish from the 1. 2. 3. used in the first-level headings.

see https://github.com/cmu-delphi/www-main/pull/170

**Comment by tildechris** [comment]
@ryantibs, as I stated in (#179)[https://github.com/cmu-delphi/www-main/pull/179#issuecomment-746511038], there are general guidelines for line lengths and readability.  Sam's change there puts us a bit over the maximum recommended value, but as you point out, it feels a little more balanced with the figures.

We definitely don't want to go wider than that, but I'm ok with making it a bit wider.

**Comment by ryantibs** [comment]
I think we can close this issue, which I'll do now.
