### ISSUE TITLE
Remove indicator list from Data & Methods page

### ISSUE THREAD

**Issue by capnrefsmmat** [cmu-delphi/www-main#171]
The [Data and Methods](https://delphi.cmu.edu/covidcast/methodology/) page currently lists and describes all of our indicators. That's no longer necessary now that the map has the "?" popup with full descriptions. We should remove this section so the page starts with what's under the "About Our Methodology" section, merging the paragraphs about how our data is public in the Epidata API into one opening paragraph. We can also link to the indicators repo and say that code for generating  all these indicators is public and open-source.

**Comment by sgratzl** [comment]
the page has been removed, see #169
