### ISSUE TITLE
Allow for an easier way to generate only changed blog posts.

### ISSUE THREAD

**Issue by tildechris** [cmu-delphi/www-main#176]
Currently blogdown isn't that sophisticated in choosing which Rmds to regenerate.  Since all of our notebooks use the API, a full build is very long.  

We should investigate a method to allow authors to only have to generate the Rmds they change.

**Comment by sgratzl** [comment]
we switched to an `md5sum` based approach + one can explictly trigger buliding just one Rmd file by executing: 

```
Rscript -e 'blogdown::build_site(local=TRUE, run_hugo=FALSE, build_rmd="content/blog/<NAME>.Rmd")'
```
where `<NAME>` should be the name of the file

**Comment by sgratzl** [comment]
closing the method described above should be fine for now
