### ISSUE TITLE
consider using JPG/webp images for hero images / banner...

### ISSUE THREAD

**Issue by sgratzl** [cmu-delphi/www-main#180]
e.g. 2MB for https://github.com/cmu-delphi/www-main/blob/sgratzl/docker-fixes/static/images/landing-page/hero-images/landing-pg_hero-img-2_Pancasting_%20forecasting%20epidemics%20from%20provisional%20data.png is too much in my opinion

**Comment by tildechris** [comment]
Agree.  In fact, we should go through all of the Chrome/Lighthouse recommendations.  I will open another issue.
