### ISSUE TITLE
Use "explore" wording the the new navigation

### ISSUE THREAD

**Issue by tildechris** [cmu-delphi/www-main#263]
Let's use "explore" in the COVIDcast navigation, which matches more towards the intended user-journey.

* "Location Overview" -> "Explore a Location"
* "Indicator Details" -> "Explore an Indicator"

Also, previous, we had dropped "Indicator Details" from the nav entirely, with the thinking that uses can get there from the Location page, but locations and indicators are co-equals as dimension and we can encourage journeys starting from either aspect.

**Comment by tildechris** [comment]
Reached consensus in a meeting: Keep the "Explore a X" headers and then add an H2 just beneath the indicator drop down to give visual prominence to the indicator type.

In the "explore a location" add an H2 restating the location name.

**Comment by sgratzl** [comment]
see https://github.com/cmu-delphi/www-covidcast/pull/829#issuecomment-801326589
