### ISSUE TITLE
Create a new "NEWS" page

### ISSUE THREAD

**Issue by Letsgohyde** [cmu-delphi/www-main#266]
We don't have a place to exhibit news and updates. Here's a spec where we could add one to the "About" page: https://docs.google.com/document/d/1j6xbBzXzoAaWEPLh06CmU1vvJ6ZppXjM3UtwJiFJOHw/edit#heading=h.c41ly7qxm8e5

**Comment by Letsgohyde** [comment]
Consider another option for images since people aren't adding them. 
1. Color
2. Texture
3. Typography

**Comment by sgratzl** [comment]
first possible implementation in https://staging.delphi.cmu.edu/about/news/

**Comment by Letsgohyde** [comment]
Thanks @sgratzl - This is coming along. Here are some copy edits. 

Update Page header text
- [ ] Delphi Team News 

Updates to posts
Welcome Fellows
- [ ] Change to "13 Google fellows join Delphi for 6 months

COVIDcast
- [ ] Change to "Launch of COVIDcast v1

COVID-19 
- [ ] Update to "Delphi shifts focus to COVID-19"

Center of Excellence
- [ ] Update to "Delphi named 'Center of Excellence' "

Again
- [ ] Update to "Delphi wins 2017-2018 forecasting challenge" 

Again
- [ ] Update to "Delphi wins  2016-2017 forecasting challenge" 

Top 
- [ ] Update to "Delphi wins 2015-2016 forecasting challenge" 


---------

Layout Feedback
- [ ] Add 64px spacing between header and 1st post. 
- [ ] Add 64px spacing between last post and footer.
