### ISSUE TITLE
update COVIDcast landing image and social preview image

### ISSUE THREAD

**Issue by sgratzl** [cmu-delphi/www-main#271]
since with the new design it has been outdated.

what about a picture of our new hex grid map?

**Comment by Letsgohyde** [comment]
1x version
![Forecast Evaluation Dashboard_hero-img_v1_1x](https://user-images.githubusercontent.com/7318770/111855792-d8bab300-88e3-11eb-8cfa-b76a4c6da9b1.png)

2x version
<img width="1440" alt="Forecast Evaluation Dashboard_hero-img_v1_2x" src="https://user-images.githubusercontent.com/7318770/111855836-1a4b5e00-88e4-11eb-9650-daacb9c885fe.png">

Hero image spec and copy
![Forecast Evaluation Dashboard_hero-img_v1_complete spec](https://user-images.githubusercontent.com/7318770/111855856-35b66900-88e4-11eb-994c-1326381b682c.png)
