### ISSUE TITLE
USA-level cases missing in Feb

### ISSUE THREAD

**Issue by philmcguinn** [cmu-delphi/www-main#272]
![Screen Shot 2021-03-19 at 8 02 15 AM](https://user-images.githubusercontent.com/71901127/111801323-14289380-888a-11eb-9a75-c5d939d64940.png)

For some reason it appears that we have no COVID cases at the US level for a large swath of February (see screenshot), which doesn't match what is showing on the map. Each state has something like 10-30 cases per 100k.

**Comment by sgratzl** [comment]
I think this is a known issue that the engineering team is about to fix

**Comment by philmcguinn** [comment]
Looks good now, thanks.
