### ISSUE TITLE
broken links on publications page

### ISSUE THREAD

**Issue by sgratzl** [cmu-delphi/www-main#313]
several links on the publication page are broken:

https://delphi.cmu.edu/about/publications/

such as:
 * https://delphi.cmu.edu/~lcbrooks/brooks2020pancasting.pdf
 * https://delphi.cmu.edu/files/PredictingThePredictable_13-04-03.pdf
 * https://delphi.cmu.edu/~dfarrow/thesis.pdf

@korlaxxalrok regarding the two personal spaces `~lcbrooks` is there something missing in the config? Regarding the other one, did we move it to web-delphi?

**Comment by korlaxxalrok** [comment]
I can add proxy_pass blocks for those personal spaces and send the traffic to the primary server instead of the docker hosts.

We must have forgotten to move the other one.

**Comment by korlaxxalrok** [comment]
I added the config for all of these and they load now. Probably a better way to do it, but I suppose we need to preserve these links for now. Check it out, see if it looks good to you.

**Comment by sgratzl** [comment]
regarding the `/files` one, I think we should move that to the web-delphi space

**Comment by korlaxxalrok** [comment]
Cool. Do you have access? If not, I'll move it. And then we just need a link update, eh?

**Comment by sgratzl** [comment]
> Cool. Do you have access? If not, I'll move it. And then we just need a link update, eh?

no I don't have access so far

**Comment by sgratzl** [comment]
fixed
