### ISSUE TITLE
COVIDcast page

### ISSUE THREAD

**Issue by tildechris** [cmu-delphi/www-main#33]
Implement the redesigned COVIDcast page.

The COVIDcast visualization assets should be referred to their published URLs.  We can assume that these are hosted on netlify for now.

**Comment by sgratzl** [comment]
see https://github.com/cmu-delphi/www-main/pull/27. But we have to decide which version of COVIDCast we wanna integrate, since small adaptations are required. The current linked pull request preview is one based on my uikit adaptations
