### ISSUE TITLE
Create a contact page

### ISSUE THREAD

**Issue by sgratzl** [cmu-delphi/www-main#347]
e.g. /about/contact

generalized version of #346 

notes
 * we cannot provide a contact (HTML) form, since there is no server side that could handle the submission and send a mail out

**Comment by Letsgohyde** [comment]
Thanks for getting this started. 

@sgratzl per your comment on how a form might not work on the site, would you advice we just add a email address in the footer?

**Comment by sgratzl** [comment]
> @sgratzl per your comment on how a form might not work on the site, would you advice we just add a email address in the footer?

depends on whether we wanna include all different kind of email addresses by subject as described in #346. As I said so far we don't have a server side that I'm aware of that could sent out e-mails

**Comment by krivard** [comment]
@christymelucci has a draft google form which will help us monitor incoming messages more easily than just posting an email address -- we're discussing it early this afternoon and i should be able to present next steps at the viz meeting

**Comment by krivard** [comment]
Under **Contact** in the footer please make the following changes:
* `Submit Feedback`--> `Website feedback`
* add `All other inquiries` as link to [the general-purpose contact form](https://docs.google.com/forms/d/e/1FAIpQLScqgT1fKZr5VWBfsaSp-DNaN03aV6EoZU4YljIzHJ1Wl_zmtg/viewform)
