### ISSUE TITLE
Correct hero image for indicators paper

### ISSUE THREAD

**Issue by ryantibs** [cmu-delphi/www-main#464]
When we go to update the carousel, I'm not sure where to find the large hero images for any given publication.  In content/about/publications/images/, we seem to have images of all different sizes, but not necessarily the big wide format that we need for the hero image. 

I'm looking in particular for a big wide version of indicators.jpg.  Thanks!

**Comment by sgratzl** [comment]
here are the carousel images located: https://github.com/cmu-delphi/www-main/tree/dev/assets/images/landing-page/hero-images

**Comment by ryantibs** [comment]
Yes thanks for that @sgratzl, but perhaps it wasn't clear what I meant: I'm looking for the hero-style analog of a particular image used on the publication page, content/about/publications/images/indicators.jpg.  And that hero-style analog doesn't appear in the carousel directory at this point.  Maybe it exists elsewhere, and I was guessing @Letsgohyde knows where since I guessed he was the one who chose these images.

**Comment by sgratzl** [comment]
this file was added by @christymelucci https://github.com/cmu-delphi/www-main/commits/ryan/edits/content/about/publications/images/indicators.jpg.

**Comment by ryantibs** [comment]
I think this must have gotten lost a bit but I noticed that the carousel image is still not the right one.  It's certainly not a big deal, but if it's easy to find the right one @christymelucci @krivard then we should swap it out.

**Comment by krivard** [comment]
In general:
* whoever adds a publication picks a 240x300 image and puts it in `content/about/publications/images`
* whoever adds a card to the carousel picks a 1440x500 image and puts it in `assets/images/landing-page/hero-images`
* anyone looking for the person who picked a publication image can find that information in [the commit history for that image](https://github.com/cmu-delphi/www-main/commits/dev/content/about/publications/images/indicators.jpg)

Not all publications are highlighted in the carousel, so not all publication images need to also look good in 1440x500 format. Publication images are portrait, while carousel images are landscape; it's not easy to find a single image that looks attractive in both crops.

For this particular image ([the original is here on unsplash](https://unsplash.com/photos/5hZJVGPG6vo)), you can either have the entire balloon, or the entire scientist holding the balloon; you can't have both in the crop. It's also backlit, so you get the bright red jacket and the silhouettes of the other scientists against the pale horizon, which can make the carousel text illegible depending on the exact crop.

Here are some quick mockups:
![image](https://user-images.githubusercontent.com/1158666/141504340-9743e2bf-bdfa-40fd-9371-0c9a337e71a1.png)

Preferences?

**Comment by ryantibs** [comment]
Thanks Katie, I understand all that workflow and I tried to abide by it.  The commit history, as Sam pointed to already above, revealed that Christy picked that publication image.  I was just waiting on Christy to find the landscape version because it wasn't in the repo.

Any three of your mockups look good.  I guess I like the middle one the most.
