### ISSUE TITLE
Replace placeholder image for current news items

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/www-main#544]
#535 added support for news item images, but they're currently all set to a placeholder. We don't necessarily need a different image for each news item, just the most recent ones that will show up on the frontpage. The rest are optional maybe? cc @ryantibs 

* [ ] 2021_05_12_spaig_award.md
* [ ] 2020_12_chng_partnership.md
* [ ] 2020_10_fellows.md
* [ ] 2020_04_covidcast.md
* [ ] 2020_03_covid.md
* [ ] 2019_10_CenterOfExcellence.md
* [ ] 2018_11.md (Delphi Wins 2017-2018 Forecasting Challenge)
* [ ] 2017_10.md (Delphi Wins 2016-2017 Forecasting Challenge)
* [ ] 2016_12.md (Delphi Wins 2015-2016 Forecasting Challenge)

**Comment by ryantibs** [comment]
Sure, relative priority here would be to fix the ones that appear on the front page definitely.

Since this wouldn't be too hard (I imagine many times it's just taking a screenshot of the relevant news posting), we could still do the others for completeness, eventually.
