### ISSUE TITLE
Mobile view of COVIDcast page is broken

### ISSUE THREAD

**Issue by tildechris** [cmu-delphi/www-main#72]
On the dev branch, the responsive small view of COVIDcast hides nearly the entire interface:

![image](https://user-images.githubusercontent.com/46794497/99822102-cd679e80-2b20-11eb-9b26-454706eb49f4.png)

Using the map on a smaller device is really tough, but they should be able to at least see it.  We should test this fix in both landscape and portrait mode.

**Comment by sgratzl** [comment]
see also #76
