### ISSUE TITLE
Set nav to transition to mobile nav at 1000px width

### ISSUE THREAD

**Issue by Letsgohyde** [cmu-delphi/www-main#75]
Global nav wraps to vertical rather than being hidden in the menu. 
![Screen Shot 2020-11-20 at 11 24 55 AM](https://user-images.githubusercontent.com/7318770/99842631-115ca280-2b25-11eb-853c-43581fffa3da.png)

**Comment by Letsgohyde** [comment]
Currently the nav snaps to mobile view at about 685px,  however the tabs become hidden and. don't truncate to stay in view. 

Let's set the nav to transition into the hamburger menu at 1000px till we can redesign the nav to respond better. 

![Screen Shot 2020-11-20 at 11 47 52 AM](https://user-images.githubusercontent.com/7318770/99843426-677e1580-2b26-11eb-8ea5-0d5e24ef384b.png)
![Screen Shot 2020-11-20 at 11 48 05 AM](https://user-images.githubusercontent.com/7318770/99843445-6cdb6000-2b26-11eb-8ae6-6c0163277bc2.png)

**Comment by sgratzl** [comment]
fixed with #82
