### ISSUE TITLE
V2 Iteration: readjusting size for covidcast page

### ISSUE THREAD

**Issue by jennyxxdance** [cmu-delphi/www-main#76]
The covidcast site currently seems very narrow in comparison to our previous launch (both images attached below): <img width="1388" alt="Screen Shot 2020-11-20 at 2 59 47 PM" src="https://user-images.githubusercontent.com/66391749/99844491-2810f280-2b41-11eb-8f08-9b6c881720ea.png">
<img width="1391" alt="Screen Shot 2020-11-20 at 3 00 11 PM" src="https://user-images.githubusercontent.com/66391749/99844494-29421f80-2b41-11eb-8a8b-4e95f59ad816.png">

**Comment by sgratzl** [comment]
as in the previous version the covidcast map takes up the remaining available vertical space. With the new design the footer takes up a lot of it.

**Comment by tildechris** [comment]
Is this fix in covidcast or www-main? (or both?)

**Comment by sgratzl** [comment]
www-main defines the space which covidcast should fill, thus imo www-main

**Comment by tildechris** [comment]
Noted.

**Comment by sgratzl** [comment]
what is the desired layout, tho? Fitting the whole content on a single page was intentional so far. This allows that the mouse wheel can be used to zoom the map.

**Comment by jennyxxdance** [comment]
I think the content layout could be re-scaled to around a single page because for now due to limited space and bigger footer taking up almost one third of the space, I think it gives less emphasis and room for covidcast map exploration.
