### ISSUE TITLE
Change the order of the Leaders on the Team Page

### ISSUE THREAD

**Issue by christymelucci** [cmu-delphi/www-main#807]
It would be great if Peter Jhon could be placed after Roni and Ryan.

**Peter Jhon requested this change.**

**Comment by krivard** [comment]
Some places to start:
* [team page HTML template](https://github.com/cmu-delphi/www-main/blob/dev/themes/delphi/layouts/_default/team.html)
* [team page content definition](https://github.com/cmu-delphi/www-main/blob/dev/content/about/team/index.md?plain=1)
* [team members metadata file](https://github.com/cmu-delphi/www-main/blob/dev/content/people/index.md?plain=1)
* [`team` shortcode HTML definition](https://github.com/cmu-delphi/www-main/blob/dev/themes/delphi/layouts/shortcodes/team.html)
