### ISSUE TITLE
Team photos spacing

### ISSUE THREAD

**Issue by jennyxxdance** [cmu-delphi/www-main#81]
Here's our current version on [dev version](https://cmu-delphi-main.netlify.app/about/team/): 
<img width="195" alt="Screen Shot 2020-11-20 at 3 10 26 PM" src="https://user-images.githubusercontent.com/66391749/99845447-aae67d00-2b42-11eb-9f54-95bc9513a276.png">

and here's our proposed version with spaced out text from the image
<img width="386" alt="Screen Shot 2020-11-20 at 3 10 12 PM" src="https://user-images.githubusercontent.com/66391749/99845497-be91e380-2b42-11eb-94ab-64b487f6231f.png">

**Comment by sgratzl** [comment]
current version: 

![image](https://user-images.githubusercontent.com/4129778/113167391-ada05f80-9211-11eb-8b5e-10c95880c58b.png)
