### ISSUE TITLE
Add Engineering Lead position to Careers page

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/www-main#816]
Eng Lead position is posted!: [Software Engineering Manager](https://cmu.wd5.myworkdayjobs.com/en-US/CMU/job/Software-Engineering-Manager---School-of-Computer-Science---MLD_2020065-1)

We should add this to the Careers page asap.

[Here's the directory with all the job blurbs](https://github.com/cmu-delphi/www-main/tree/dev/content/about/careers/headless), the easiest way is to make a copy of an existing one and then change the metadata to fit.

**Comment by dshemetov** [comment]
We added this last week [here](https://delphi.cmu.edu/about/careers/), but there are still some grammatical oddities in the blurb that we should probably fix
