### ISSUE TITLE
Switch to a safer method for API authentication in blog posts

### ISSUE THREAD

**Issue by krivard** [cmu-delphi/www-main#821]
In order to permit the blog to build, we had to add API keys to the blog posts that hit the API (#819). This places an open API key in the blog sources, which while not as easy to troll as making them visible in the blog posts themselves, is still suboptimal.

We should modify the blog build procedure to permit the API key to be stored in an encrypted format, then deactivate the current key and replace it with a new one.

**Comment by minhkhul** [comment]
closed. we hid the key using github secrets while working on [this](https://github.com/cmu-delphi/www-main/pull/891). repo admin can make this change.
