### ISSUE TITLE
Listing Epidatr as a tool

### ISSUE THREAD

**Issue by dsweber2** [cmu-delphi/www-main#864]
I noticed that epidatr isn't listed [here](https://delphi.cmu.edu/tools/); we may want to replace the COVIDCAST R package link with one to epidatr, or add it additionally.

**Comment by rlunde** [comment]
@dsweber2 do you think we should mention epidatpy there as well? (I know it's not as far along.)

**Comment by dshemetov** [comment]
If we do, we should mention that epidatpy is in very early alpha stages.

**Comment by rlunde** [comment]
Probably best to wait until we've had a chance to evaluate where we are and plan for an MVP release?

**Comment by dshemetov** [comment]
Agreed, that package is really behind
