### ISSUE TITLE
"Our API" leads to COVIDCast app

### ISSUE THREAD

**Issue by sgratzl** [cmu-delphi/www-main#87]
atm in the landing page, the subsection:

![image](https://user-images.githubusercontent.com/4129778/99969111-06de1b00-2d68-11eb-9fea-627cdb686866.png)

leads to the COVIDCast app which sounds to me misleading as it states "Our API" and the page doesn't give much information about that. should we link to the API page https://cmu-delphi.github.io/delphi-epidata/ instead?

**Comment by jennyxxdance** [comment]
Yes, that image/"learn more" should link to api page not covidcast! Thank you!
