### ISSUE TITLE
Consider adding a table-of-contents for blog posts

### ISSUE THREAD

**Issue by tildechris** [cmu-delphi/www-main#92]
With a new line-width, there is a lot of white space in the blog posts.  The line-width also makes the posts longer to scroll through.

We should investigate adding a TOC to make navigation easier.

**Comment by sgratzl** [comment]
related links
 * https://stackoverflow.com/questions/46119371/create-a-table-of-contents-toc-in-a-post-with-blogdown-package#47745617
 * https://getuikit.com/docs/scrollspy#scrollspy-nav

tho it requires some custom JavaScript that converts the plain HTML navigation from blogdown into the UIkit navigation
