### ISSUE TITLE
FLaSH paper listing is missing publication year

### ISSUE THREAD

**Issue by melange396** [cmu-delphi/www-main#929]
This paper needs a `year:` field like the others have:
https://github.com/cmu-delphi/www-main/blob/88ce1ff9568ebb87047188cbef54c0d805528654/content/about/publications/index.md?plain=1#L4-L8

See it live here: https://delphi.cmu.edu/about/publications/

@Ananya-Joshi should it be 2023?

**Comment by Ananya-Joshi** [comment]
It's 2023! on my way to update it - thank you!
