### ISSUE TITLE
Replace "About COVIDcast" page with an Epidata page

### ISSUE THREAD

**Issue by nmdefries** [cmu-delphi/www-main#983]
The "About COVIDcast" page should be replaced with an "About Delphi Epidata" page, with the first section of it replaced by the following (adapted from "About COVIDcast").  Suggestions welcome.

-----------------------------------------------------------------------------------------------------------------------------------------------------
# About Delphi Epidata

Delphi Epidata is a database platform, repository and API for epidemiological signals (also called "indicators").  It was launched in 2016 and significantly revamped during the pandemic.  Delphi Epidata was purpose-designed for hosting signals for epidemic and pandemic detection, tracking and forecasting.  It has built-in support for data versioning, calendar reporting effects, anomaly and trend detection, backfill projection, privacy-based censoring, and geographic, temporal and demographic aggregation.  The current Delphi Epidata repository contains over 500 different signals, tracking flu, Covid-19, denge, norovirus and other pathogens, and covering all rungs of the severity pyramid.  The COVID-19 related portion of Delphi Epidata is also known as COVIDcast.

1. We procure unique data streams that reflect epidemic and pandemic activity from a wide variety of sources, and extract from them disease-related signals. These signals cover every nearly every rung of the [severity pyramid](https://deploy-preview-962--cmu-delphi-main.netlify.app/epidemic-signals/#severity-pyramid).  The COVID-19 related signals, known collectively as COVIDcast, constitute what we believe may be the nation’s largest public repository of real-time, geographically-detailed indicators of COVID-19 activity in the U.S.

2. We make all such indicators freely available to the greatest extent allowable, using a [public API](https://cmu-delphi.github.io/delphi-epidata/api/covidcast.html) which is updated with new data daily. We also provide associated [R](https://cmu-delphi.github.io/covidcast/covidcastR/) and [Python](https://cmu-delphi.github.io/covidcast/covidcast-py/html/) packages, and a [dashboard](https://deploy-preview-962--cmu-delphi-main.netlify.app/covidcast/) to visualize a core set of indicators.

3. Some of the underlying data sources (on which these indicators are built) would not exist or be publicly available without Delphi’s efforts. These include a massive national daily survey called the [COVID-19 Trends and Impact Survey (CTIS)](https://deploy-preview-962--cmu-delphi-main.netlify.app/epidemic-signals/ctis/) that we have deployed in partnership with Facebook, which has been taken by over 25 million Americans during 2020-2022; and an enormous database of de-identified medical insurance claims, covering more than 35% of the U.S. population, made possible through health system partners including Change Healthcare.

4. We support and advise the U.S. CDC (in collaboration with the [Reich Lab](https://reichlab.io/)) on short-term forecasting, which includes creating and evaluating ensemble forecasts out of the models submitted to e.g. the [COVID-19 Forecast Hub](https://covid19forecasthub.org/), serving as the basis for the [CDC’s official forecast communications](https://www.cdc.gov/coronavirus/2019-ncov/covid-data/forecasting-us.html).

**Comment by melange396** [comment]
as part of this, we should:
- note/acknowledge the name change -- something like "`Delphi Epidata (nee "COVIDcast")`" or "`(the platform formerly known as COVIDcast)`"
- link to a deeper explanation of why ( https://github.com/cmu-delphi/www-main/issues/1000 )

**Comment by RoniRos** [comment]
Here is my updated version.  I would appreciate vetting from anyone, especially @carlynvandyke for language and content, and @nmdefries for the discussion of and links to the tools.

# About Delphi Epidata (including COVIDcast)

Delphi Epidata is a database platform, repository, and API for epidemiological signals (also called "indicators"). It was launched in 2016 and significantly revamped during the pandemic. Delphi Epidata was purpose-designed for hosting signals for epidemic and pandemic detection, tracking and forecasting. It has built-in support for data versioning, calendar reporting effects, anomaly and trend detection, backfill projection, privacy-based censoring, and geographic, temporal and demographic breakdown and aggregation. The current Delphi Epidata repository contains over 500 different signals, tracking flu, Covid-19, denge, norovirus and other pathogens, and covering all rungs of the [severity pyramid](https://deploy-preview-962--cmu-delphi-main.netlify.app/epidemic-signals/#severity-pyramid).

We procure data streams that reflect epidemic and pandemic activity from a wide variety of sources -- including unique industry partnerships and scraping of publicly available data -- and extract from them in real-time disease-related signals at the finest possible geographic, demographic and temporal granularity.  

The COVID-19 related portion of Delphi Epidata is also known as **COVIDcast**, and constitute what we believe may be the largest public repository of real-time, geographically-detailed indicators of COVID-19 activity in the U.S.

We make all our signals freely available in real-time to the greatest extent allowable, using a [public API](https://cmu-delphi.github.io/delphi-epidata/) which is updated with new data daily. We also provide:

- a [signal discovery](https://delphi.cmu.edu/signals/) tool, to explore what epi-signals are available in Delphi Epidata and elsewhere in the community
- a general [signal visualization](https://deploy-preview-996--cmu-delphi-main.netlify.app/epivis/) tool
- a [Covid-19 dashboard](https://deploy-preview-996--cmu-delphi-main.netlify.app/covidcast/) and a "classic" [map-based version](https://deploy-preview-996--cmu-delphi-main.netlify.app/covidcast/classic/) to visualize a core set of Covid-19 indicators
- a [Covid-19 signal export](https://deploy-preview-996--cmu-delphi-main.netlify.app/covidcast/export/) app, a [dashboard builder](https://deploy-preview-996--cmu-delphi-main.netlify.app/covidcast/dashboard/), and more
- [R](https://cmu-delphi.github.io/epidatr/) and [Python](https://github.com/cmu-delphi/epidatpy) packages to extract signals from the Epidata repository, and R packages to further [process them](https://cmu-delphi.github.io/epiprocess/) and to create [epidemic forecasting models](https://cmu-delphi.github.io/epipredict/)

Some of the underlying data from which these signals are extracted would not exist or be publicly available without Delphi’s efforts. These include a massive national daily survey called the [COVID-19 Trends and Impact Survey (CTIS)](https://deploy-preview-962--cmu-delphi-main.netlify.app/epidemic-signals/ctis/) that we have deployed in partnership with Facebook, which has been taken by over 25 million Americans during 2020-2022; and aggregated counts extracted from an enormous database of de-identified medical insurance claims, covering more than 35% of the U.S. population, made possible through health system partners including Change Healthcare.

**Comment by carlynvandyke** [comment]
- Quick spelling/style fixes:
> The Delphi Epidata repository contains over 500 different current or historical signals, tracking flu, C**OVID**-19, deng**u**e, norovirus and other pathogens, and covering all rungs of the [severity pyramid](https://deploy-preview-962--cmu-delphi-main.netlify.app/epidemic-signals/#severity-pyramid).

- Actually, do we want "Covid-19" or "COVID-19" to be our standard? I think I prefer the non-caps version.

- Do we want to say that the dashboard is only Covid-19? We do have a few flu signals in there (and in the signal export tool).

Otherwise I think the text looks great!

Re: the 8/1 additions: We have [the full publications page here](https://delphi.cmu.edu/about/publications/). Do we want to re-list just Epidata-related articles here? If so, Christy has had an idea about how to reorganize our publications that would make this a lot easier to keep up-to-date, I think.

**Comment by RoniRos** [comment]
Thanks.

> Actually, do we want "Covid-19" or "COVID-19" to be our standard? I think I prefer the non-caps version.

I too prefer to avoid all caps whenever possible.  But in this case, WHO guidelines and CDC usage is always "COVID-19", so I think we should stick with that.  In casual text, I personally feel comfortable sometimes using "Covid" (without the "19" part).
Also, "COVIDcast" should stay "COVIDcast".

I edited-in-place above "Covid-19" into "COVID-19" throughout

> Do we want to say that the dashboard is only Covid-19? We do have a few flu signals in there (and in the signal export tool).

Good catch.  I fixed it in place.

> Re: the 8/1 additions: We have [the full publications page here](https://delphi.cmu.edu/about/publications/). Do we want to re-list just Epidata-related articles here? 

Yes, I think there is value in listing some Epidata-specific publications here.

> If so, Christy has had an idea about how to reorganize our publications that would make this a lot easier to keep up-to-date, I think.

That's cool, we should pursue it.  I am not sure we would want to put _every_ Epidata-related publication here, we may prefer to maintain editorial discretion.  But an automated method would be better than not updating it at all.

I will also add a link to Ryan's Tools talk.  @ryantibs I hope that's okay!

**Comment by nmdefries** [comment]
Also need to change menu title

**Comment by RoniRos** [comment]
> Also need to change menu title

Let's make it "About Delphi Epidata & COVIDcast"

**Comment by melange396** [comment]
this is live!  https://delphi.cmu.edu/epidemic-signals/about-delphi-epidata-covidcast/

(content went in w/ #996)
