### ISSUE TITLE
Team page updates

### ISSUE THREAD

**Issue by tildechris** [cmu-delphi/www-main#99]
As per Ryan:

* Many “Interns” are completely gone (Amartya, Robin, Wael, Vishaka) and others are mostly gone (Eu Jing?).  I would check with Katie but I think at least Amartya, Robin, Wael, Vishaka can be moved to “Past Members”.
* EJ Fox is not working with us anymore and can be moved from “Contractors” to “Past Members”
* In “Contributors”, we should certainly move “Andrew Chin” to “Core Members”.   I believe we can move many contributors here to “Past Members” as well.
* Finally, “Core Members” is missing several people: Nat, Wichada, Kari … at least.

We should audit the full list and update everybody's status.

**Comment by dajmcdon** [comment]
Entirely self-serving: I'm still not here!

**Comment by sgratzl** [comment]
@bweaver-work any idea when I the list (e.g. CSV) and the images are available?

**Comment by bweaver-work** [comment]
I'll make initial edits to the index.md directly, and then send your way for review by tomorrow. I still need to confirm a few staffing changes.

**Comment by sgratzl** [comment]
> I'll make initial edits to the index.md directly, and then send your way for review by tomorrow. I still need to confirm a few staffing changes.

sounds good. Dont' forget to work in your own branch (starting from dev) and create a PR when you are done which merges it back to the dev branch.

**Comment by sgratzl** [comment]
can we close this issue?

**Comment by tildechris** [comment]
Closed with #160.
